[package]
name = "learning-rust"
version = "0.1.0"
authors = ["Muhammad Sandy Gunawan <sandyz.boyz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
